### ISSUE TITLE
Pre-filled xml doc snippets are sometimes not created for xUnit tests

### ISSUE THREAD

**Issue by KGergo88** [jpfeiffer16/angeldoc-vscode#1]
Thank you for your work on this extension! :)

I would like to document my xUnit tests, for example something like this:
```
using Xunit;

namespace MyNameSpace
{
    public class MyTestClass
    {
        [Fact]
        void MyTestThatNeedsToBeDocumented(int myVariable)
        {

        }
    }
}
```

After I enter the `///` over the `[Fact]` or the function name, there is a blink, the `///` is being removed but no snippets are generated.
With some other code I was able to generate them over the function name.

VSCode version:
```
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
```

Please let me know if you need further infos.

**Comment by jpfeiffer16** [comment]
@KGergo88 thank you for your interest! I'll take a look and see what I find.

**Comment by jpfeiffer16** [comment]
@KGergo88 I pushed a new package version that should fix this. Can you give it a try?

**Comment by KGergo88** [comment]
Thanks! :)

It works now if it is written over the function name. It still fails if I do it over an Attribute, but I can live with this.

**Comment by jpfeiffer16** [comment]
@KGergo88 yea. That is a good point. I have had the same thought. I put in an issue for this [here](https://github.com/jpfeiffer16/AngelDoc/issues/11) if you want to watch it. No promises for if I get to it soon, but you can track it there if you want.
